# This is a basic workflow to help you get started with Azure VS Code

name: Azure VS Code

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab. Please run just once
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create the app service and vs code webapp
      - run: |
          group=rg-devops-sura-rrsantos-dev
          location=eastus
          plan=plan-devops-sura-rrsantos-dev
          app=app-devops-sura-vscode-rrsantos-dev
          sku=P3V2
          image=bencdr/code-server-azure
          repo=https://github.com/rrsatos/Devops.git
          az configure --defaults group=$group location=$location
          az appservice plan create --name $plan --is-linux --sku $sku
       
